project:
  type: website
  output-dir: docs

highlight-style: a11y

execute:
  cache: true
  freeze: auto

website:
  announcement: 
    icon: info-circle
    dismissable: false
    content: "**Alert** - this is some information that you should pay attention to"
    type: primary
    position: above-navbar
  back-to-top-navigation: true
  reader-mode: false
  page-navigation: true
  title: "FPF AgroScience"
  search:
    show-item-context: true
    type: overlay
  navbar:
    # logo: imagens/logo.png
    pinned: true
    border: false
    left:
      - href: index.qmd
        text: Home
      - href: campo.qmd
        text: Serviços de campo
      - href: laboratório.qmd
        text: Serviços de laboratório
      - href: contato.qmd
        text: Contato
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/raphaelfitopatologia
      - icon: instagram
        href: https://www.instagram.com/invites/contact/?i=xk2vhn0e4rad&utm_content=2owlczy
      - icon: whatsapp
        href: https://wa.me/5564992915590
  page-footer:
    left: © <span id='copyright-year'></span>. All rights reserved.
    background: "#375A7F"
format:
  html:
    page-layout: full
    include-after-body: footer.html
    # theme:
    #   light: cosmo
    #   dark: darkly
    css: styles.css
    toc: false
    reader-mode: false
editor: visual
